combineDistanceThreshold: 0.75
pdf_std: 475
confidenceThreshold: 0.3
NumOfParticles: 3500
NumberOfParticlesToReset: 20
windDir: 0

mapPercent: 0.005
percentTheta: 0.0055
percentQ: 0.015
percentV: 0.01
percentDy: 0.01
percentDz: 0.01

X_u: 4.2
X_l: 0

Y_u: 2.67
Y_l: 0

Z_u: 0.2
Z_l: 0.2

Theta_range: 0.3
Theta_u: 0.523599
Theta_l: -0.523599

# These parameters should work for the real life plume if you change them I
# will kill you

Q_u: 4.083e-5
Q_l: 1.082e-5

V_u : 3.0
V_l : 2.0

Dy_u : 3.0e-2
Dy_l : 5.0e-3

Dz_u : 4.0e-9
Dz_l : 1.0e-9
